/** Catalog-only Tiny Treats models; scene assignment is intentionally separate. */

export const TINY_TREATS_COLLECTIONS = ["baked-goods", "charming-kitchen"] as const;

export const BAKED_GOODS_MODELS = [
  "baguette",
  "baguette_half",
  "baguette_slice",
  "bread",
  "bread_half",
  "bread_roll",
  "bread_slice",
  "cake_birthday",
  "cake_birthday_cut",
  "cake_birthday_slice",
  "cake_chocolate",
  "cake_chocolate_cut",
  "cake_chocolate_slice",
  "cake_strawberry",
  "cake_strawberry_cut",
  "cake_strawberry_slice",
  "cinnamon_roll",
  "cookie",
  "croissant",
  "cupcake",
  "donut",
  "donut_chocolate",
  "donut_pink",
  "muffin",
  "pie_apple",
  "pie_apple_cut",
  "pie_apple_slice",
  "pie_cherry",
  "pie_cherry_cut",
  "pie_cherry_slice",
  "waffle",
  "waffle_stacked",
] as const;

export const CHARMING_KITCHEN_MODELS = [
  "blinds_kitchen",
  "chair",
  "container_kitchen_A_blue",
  "container_kitchen_A_red",
  "container_kitchen_A_white",
  "container_kitchen_B_blue",
  "container_kitchen_B_red",
  "container_kitchen_B_white",
  "countertop_corner_inner",
  "countertop_counter_outer",
  "countertop_single",
  "countertop_sink",
  "countertop_straight_A",
  "countertop_straight_B",
  "countertop_straight_C",
  "cuttingboard",
  "dishrack",
  "dishrack_plates",
  "door_modular",
  "extractor_hood",
  "floor_tiles_kitchen",
  "fridge",
  "kettle",
  "knife",
  "lid",
  "mug_blue",
  "mug_red",
  "mug_yellow",
  "oven_glove",
  "pan",
  "papertowel_holder",
  "plate",
  "pot",
  "spatula",
  "spoon",
  "stove",
  "table_A",
  "table_B",
  "table_C",
  "toaster",
  "utensils_cup",
  "wall_cabinet_corner",
  "wall_cabinet_single_left",
  "wall_cabinet_single_right",
  "wall_cabinet_straight",
  "wall_knife_rack",
  "wall_modular_plain_kitchen_corner_inner_A",
  "wall_modular_plain_kitchen_corner_inner_B",
  "wall_modular_plain_kitchen_corner_outer_A",
  "wall_modular_plain_kitchen_corner_outer_B",
  "wall_modular_plain_kitchen_half_corner_inner_A",
  "wall_modular_plain_kitchen_half_corner_inner_B",
  "wall_modular_plain_kitchen_half_corner_outer_A",
  "wall_modular_plain_kitchen_half_corner_outer_B",
  "wall_modular_plain_kitchen_half_straight_A",
  "wall_modular_plain_kitchen_half_straight_B",
  "wall_modular_plain_kitchen_straight_A",
  "wall_modular_plain_kitchen_straight_B",
  "wall_modular_plain_kitchen_window_full_center_A",
  "wall_modular_plain_kitchen_window_full_center_B",
  "wall_modular_plain_kitchen_window_full_left_A",
  "wall_modular_plain_kitchen_window_full_left_B",
  "wall_modular_plain_kitchen_window_full_right_A",
  "wall_modular_plain_kitchen_window_full_right_B",
  "wall_modular_plain_kitchen_window_large_A",
  "wall_modular_plain_kitchen_window_large_B",
  "wall_modular_plain_kitchen_window_small_A",
  "wall_modular_plain_kitchen_window_small_B",
  "wall_modular_tiles_kitchen_corner_inner_A",
  "wall_modular_tiles_kitchen_corner_inner_B",
  "wall_modular_tiles_kitchen_corner_outer_A",
  "wall_modular_tiles_kitchen_corner_outer_B",
  "wall_modular_tiles_kitchen_doorway",
  "wall_modular_tiles_kitchen_half_corner_inner_A",
  "wall_modular_tiles_kitchen_half_corner_inner_B",
  "wall_modular_tiles_kitchen_half_corner_outer_A",
  "wall_modular_tiles_kitchen_half_corner_outer_B",
  "wall_modular_tiles_kitchen_half_straight_A",
  "wall_modular_tiles_kitchen_half_straight_B",
  "wall_modular_tiles_kitchen_straight_A",
  "wall_modular_tiles_kitchen_straight_B",
  "wall_modular_tiles_kitchen_window_full_center_A",
  "wall_modular_tiles_kitchen_window_full_center_B",
  "wall_modular_tiles_kitchen_window_full_left_A",
  "wall_modular_tiles_kitchen_window_full_left_B",
  "wall_modular_tiles_kitchen_window_full_right_A",
  "wall_modular_tiles_kitchen_window_full_right_B",
  "wall_modular_tiles_kitchen_window_large_A",
  "wall_modular_tiles_kitchen_window_large_B",
  "wall_modular_tiles_kitchen_window_small_A",
  "wall_modular_tiles_kitchen_window_small_B",
  "wall_papertowel_holder",
  "wall_plain_kitchen_corner_inner",
  "wall_plain_kitchen_corner_outer",
  "wall_plain_kitchen_straight",
  "wall_plain_kitchen_window_full_center",
  "wall_plain_kitchen_window_full_left",
  "wall_plain_kitchen_window_full_right",
  "wall_plain_kitchen_window_large",
  "wall_plain_kitchen_window_small",
  "wall_shelf_kitchen",
  "wall_shelf_kitchen_corner",
  "wall_shelf_kitchen_hooks",
  "wall_shelf_kitchen_hooks_decorated",
  "wall_tiles_kitchen_corner_inner",
  "wall_tiles_kitchen_corner_outer",
  "wall_tiles_kitchen_doorway",
  "wall_tiles_kitchen_straight",
  "wall_tiles_kitchen_window_full_center",
  "wall_tiles_kitchen_window_full_left",
  "wall_tiles_kitchen_window_full_right",
  "wall_tiles_kitchen_window_large",
  "wall_tiles_kitchen_window_small",
  "window_full_center_modular",
  "window_full_left_modular",
  "window_full_right_modular",
  "window_large_modular",
  "window_small_modular",
] as const;

export type TinyTreatsCollection = (typeof TINY_TREATS_COLLECTIONS)[number];
export type BakedGoodsModel = (typeof BAKED_GOODS_MODELS)[number];
export type CharmingKitchenModel = (typeof CHARMING_KITCHEN_MODELS)[number];
export type TinyTreatsModel = BakedGoodsModel | CharmingKitchenModel;

export function tinyTreatsAssetUrl(
  pluginId: string,
  collection: TinyTreatsCollection,
  model: TinyTreatsModel,
): string {
  return `/_plugins/${encodeURIComponent(pluginId)}/ui/assets/tiny-treats/${collection}/gltf/${model}.gltf`;
}
